### ISSUE TITLE
Error during the execution of BNH test

### ISSUE THREAD

**Issue by Hyzbade** [samthiriot/genlab#27]
Setup
name of the problem test: Binh and Korn "BNH"
initial number of iterations: 100
initial size of the population: 1000
value for minimization: -2147483

Notes
the execution has been stopped after the 100. iteration
the output csv file has been updated successfully

Error
833712 [glConsumeMessages] ERROR genlab.gui.jfreechart.exec.ScatterPlotExec  - Wed Apr 29 11:03:03 CEST 2015 - error during the execution: Invalid thread access
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4397)
	at org.eclipse.swt.SWT.error(SWT.java:4312)
	at org.eclipse.swt.SWT.error(SWT.java:4283)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:481)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:419)
	at org.eclipse.swt.widgets.Control.redraw(Control.java:3663)
	at org.jfree.experimental.chart.swt.ChartComposite.chartChanged(ChartComposite.java:972)
	at org.jfree.chart.JFreeChart.notifyListeners(JFreeChart.java:1515)
	at org.jfree.chart.JFreeChart.plotChanged(JFreeChart.java:1581)
	at org.jfree.chart.plot.Plot.notifyListeners(Plot.java:970)
	at org.jfree.chart.plot.Plot.fireChangeEvent(Plot.java:981)
	at org.jfree.chart.plot.Plot.axisChanged(Plot.java:1217)
	at org.jfree.chart.axis.Axis.notifyListeners(Axis.java:1222)
	at org.jfree.chart.axis.Axis.fireChangeEvent(Axis.java:1233)
	at org.jfree.chart.axis.Axis.setLabel(Axis.java:391)
	at genlab.gui.jfreechart.views.ScatterView.loadDataFromTable(ScatterView.java:76)
	at genlab.gui.jfreechart.views.ScatterView.setData(ScatterView.java:146)
	at genlab.gui.jfreechart.exec.ScatterPlotExec.displayResultsSync(ScatterPlotExec.java:56)
	at genlab.gui.algos.AbstractOpenViewAlgoExec.displayResultsAsync(AbstractOpenViewAlgoExec.java:164)
	at genlab.gui.algos.AbstractOpenViewAlgoExec.run(AbstractOpenViewAlgoExec.java:210)
	at genlab.core.exec.WorkingRunnerThread.run(WorkingRunnerThread.java:43)
833712 [glConsumeMessages] ERROR genlab.core.model.exec.WorkflowExecution  - Wed Apr 29 11:03:03 CEST 2015 - end of execution for workflow test function Bink Korn for multi-objective genetic algorithms (failure)

**Comment by samthiriot** [comment]
Corresponds to bug #22 . Thanks !
