### ISSUE TITLE
Branch dev: Unable to cast integer from gene x

### ISSUE THREAD

**Issue by Hyzbade** [samthiriot/genlab#32]
4433 [glConsumeMessages] ERROR genlab.core.exec.WorkingRunnerThread  - Wed May 06 16:12:45 CEST 2015 - task multi-objective test functions 1 raised an error:unable to cast integer from gene x
genlab.core.commons.WrongParametersException: unable to cast integer from gene x
	at genlab.core.model.meta.basics.flowtypes.DoubleFlowType.decodeFrom(DoubleFlowType.java:29)
	at genlab.core.model.meta.basics.flowtypes.DoubleFlowType.decodeFrom(DoubleFlowType.java:1)
	at genlab.core.model.meta.InputOutput.decodeFromParameters(InputOutput.java:121)
	at genlab.core.model.exec.AbstractAlgoExecution.getInputValueForInput(AbstractAlgoExecution.java:167)
	at genlab.core.model.exec.AbstractAlgoExecution.getInputValueForInput(AbstractAlgoExecution.java:177)
	at genlab.algog.algos.meta.VerificationFunctionsAlgo$1.run(VerificationFunctionsAlgo.java:150)
	at genlab.core.exec.WorkingRunnerThread.run(WorkingRunnerThread.java:43)

**Comment by samthiriot** [comment]
non reproductible... as-tu un cas d'exemple ?

**Comment by Hyzbade** [comment]
Ne t'embête pas avec ce bug pour le moment, il a probablement été généré par l'implémentation en cours. Toutefois, si tu veux le reproduire, mets toi à jour sur la branche dev, lance GenLab et lance Constr-Ex.

**Comment by samthiriot** [comment]
fixed
