### ISSUE TITLE
NSGA2 regression: nullpointerexception when there are constrainsts on the search domain

### ISSUE THREAD

**Issue by samthiriot** [samthiriot/genlab#34]
java.lang.NullPointerException
	at genlab.algog.algos.exec.NSGA2Exec.dominates(NSGA2Exec.java:70)
	at genlab.algog.algos.exec.NSGA2Exec.fastNonDominatedSort(NSGA2Exec.java:126)
	at genlab.algog.algos.exec.NSGA2Exec.analyzeLastPopulation(NSGA2Exec.java:415)
	at genlab.algog.algos.exec.NSGA2Exec.selectIndividuals(NSGA2Exec.java:425)
	at genlab.algog.algos.exec.NSGA2Exec.prepareNextGeneration(NSGA2Exec.java:699)
	at genlab.algog.algos.exec.AbstractGeneticExplorationAlgoExec.computationStateChanged(AbstractGeneticExplorationAlgoExec.java:733)
	at genlab.core.model.exec.ComputationProgressWithSteps.dispatchComputationStateChanged(ComputationProgressWithSteps.java:256)
	at genlab.core.model.exec.ComputationProgressWithSteps.setComputationState(ComputationProgressWithSteps.java:219)
	at genlab.core.model.exec.AbstractContainerExecutionSupervisor.updateProgressFromChildren(AbstractContainerExecutionSupervisor.java:340)
	at genlab.core.model.exec.AbstractContainerExecution.computationStateChanged(AbstractContainerExecution.java:108)
	at genlab.algog.algos.exec.GeneticExplorationOneGeneration.computationStateChanged(GeneticExplorationOneGeneration.java:280)
	at genlab.core.model.exec.ComputationProgressWithSteps.dispatchComputationStateChanged(ComputationProgressWithSteps.java:256)
	at genlab.core.model.exec.ComputationProgressWithSteps.setComputationState(ComputationProgressWithSteps.java:219)
	at genlab.core.model.exec.AbstractContainerExecution.updateProgressFromChildren(AbstractContainerExecution.java:191)
	at genlab.core.model.exec.AbstractContainerExecution.computationStateChanged(AbstractContainerExecution.java:108)
	at genlab.core.model.exec.ComputationProgressWithSteps.dispatchComputationStateChanged(ComputationProgressWithSteps.java:256)
	at genlab.core.model.exec.ComputationProgressWithSteps.setComputationState(ComputationProgressWithSteps.java:219)
	at genlab.algog.algos.exec.GoalExec.run(GoalExec.java:48)
	at genlab.core.exec.WorkingRunnerThread.run(WorkingRunnerThread.java:93)
661981 [glConsumeMessages] INFO genlab.algog.algos.exec.NSGA2Exec  - Thu May 07 01:18:14 CEST 2015 - Retrieved 99 individuals from the previous generation (0)
661982 [glConsumeMessages] WARN genlab.core.model.exec.ComputationProgressWithSteps  - Thu May 07 01:18:14 CEST 2015 - catched an exception while notifying listener genlab.algog.algos.exec.NSGA2Exec@1
fd586bf of computation state change (genlab.core.model.exec.ComputationProgressWithSteps@ad02020)
java.lang.NullPointerException
	at genlab.algog.algos.exec.NSGA2Exec.dominates(NSGA2Exec.java:70)
	at genlab.algog.algos.exec.NSGA2Exec.fastNonDominatedSort(NSGA2Exec.java:126)
	at genlab.algog.algos.exec.NSGA2Exec.analyzeLastPopulation(NSGA2Exec.java:415)
	at genlab.algog.algos.exec.NSGA2Exec.selectIndividuals(NSGA2Exec.java:425)
	at genlab.algog.algos.exec.NSGA2Exec.prepareNextGeneration(NSGA2Exec.java:699)
	at genlab.algog.algos.exec.AbstractGeneticExplorationAlgoExec.computationStateChanged(AbstractGeneticExplorationAlgoExec.java:733)
	at genlab.core.model.exec.ComputationProgressWithSteps.dispatchComputationStateChanged(ComputationProgressWithSteps.java:256)
	at genlab.core.model.exec.ComputationProgressWithSteps.setComputationState(ComputationProgressWithSteps.java:219)
	at genlab.core.model.exec.AbstractContainerExecutionSupervisor.updateProgressFromChildren(AbstractContainerExecutionSupervisor.java:340)
	at genlab.core.model.exec.AbstractContainerExecution.computationStateChanged(AbstractContainerExecution.java:108)
	at genlab.algog.algos.exec.GeneticExplorationOneGeneration.computationStateChanged(GeneticExplorationOneGeneration.java:280)
	at genlab.core.model.exec.ComputationProgressWithSteps.dispatchComputationStateChanged(ComputationProgressWithSteps.java:256)
	at genlab.core.model.exec.ComputationProgressWithSteps.setComputationState(ComputationProgressWithSteps.java:219)
	at genlab.core.model.exec.AbstractContainerExecution.updateProgressFromChildren(AbstractContainerExecution.java:191)
	at genlab.core.model.exec.AbstractContainerExecution.computationStateChanged(AbstractContainerExecution.java:108)
	at genlab.core.model.exec.ComputationProgressWithSteps.dispatchComputationStateChanged(ComputationProgressWithSteps.java:256)
	at genlab.core.model.exec.ComputationProgressWithSteps.setComputationState(ComputationProgressWithSteps.java:219)
	at genlab.algog.algos.exec.GoalExec.run(GoalExec.java:48)
	at genlab.core.exec.WorkingRunnerThread.run(WorkingRunnerThread.java:93)

**Comment by samthiriot** [comment]
fixed
